from faker import Faker

from functools import partial

f = Faker()

fake_data_map = {
    "name": f.name,
    "first_name": f.first_name,
    "last_name": f.last_name,
    "address": f.address,
    "text": f.text,
    "sentence": f.sentence,
    "language": f.language_code,
    "locale": f.locale,
    "city": f.city,
    "country": f.country,
    "country_code": f.country_code,
    "street_address": f.street_address,
    "license_plate": f.license_plate,
    "bank_account_number": f.bban,
    "i_bank_account_number": f.iban,
    "ean_barcode": f.ean,
    "color": f.color,
    "rgb_color": partial(f.color, color_format="rgb"),
    "hsv_color": partial(f.color, color_format="hsv"),
    "color_name": f.color_name,
    "company": f.company,
    "company_catch_phrase": f.catch_phrase,
    "cc_expire": f.credit_card_expire,
    "cc_data": f.credit_card_full,
    "cc_number": f.credit_card_number,
    "cc_provider": f.credit_card_provider,
    "cryptocurrency": f.cryptocurrency,
    "currency": f.currency,
    "date": f.date,
    "time": f.time,
    "time_series": f.time_series,
    "timezone": f.timezone,
    "coordinates": f.latlng,
    "location_on_land": f.location_on_land,
    "email": f.email,
    "domain": f.domain_name,
    "image": f.image_url,
    "ipv4": f.ipv4,
    "ipv6": f.ipv6,
    "mac": f.mac_address,
    "uri": f.uri,
    "url": f.url,
    "username": f.user_name,
    "isbn": f.isbn10,
    "job": f.job,
    "paragraph": partial(f.paragraph, nb_sentences=5),
    "paragraphs": partial(f.paragraphs, nb=5),
    "password": f.password,
    "uuid4": f.uuid4,
    "name_female": f.name_female,
    "phone": f.phone_number,
    "profile": f.profile,
    "android": f.android_platform_token,
    "ios": f.ios_platform_token,
    "linux": f.linux_platform_token,
    "mac": f.mac_platform_token,
    "windows": f.windows_platform_token,
    "chrome": f.chrome,
    "firefox": f.firefox,
    "user_agent": f.user_agent,
}